name:   $(MajorVersion).$(MinorVersion).$(BuildID)

trigger: none

jobs:
  - job: build
    timeoutInMinutes: 180
    pool:
      vmImage: 'vs2017-win2016'

    steps:
    - checkout: self
      persistCredentials: true
      clean: true

    - powershell: ./crawlgen.ps1
      displayName: 'Crawl ESI & Generate'

    - script: git add .
      displayName: "Add to Git"

    - script: git commit -m "source update"
      displayName: "Commit"

    - script: git push
      displayName: "Push to Git"


