namespace EsiStatics.Data.Universe
open System
open EsiStatics.Data.Entities
module  Constellations=
    let getConstellation id = 
      let bkt = id % 97
      match bkt with
        | 0 -> Constellations0.getConstellation id
        | 1 -> Constellations1.getConstellation id
        | 2 -> Constellations2.getConstellation id
        | 3 -> Constellations3.getConstellation id
        | 4 -> Constellations4.getConstellation id
        | 5 -> Constellations5.getConstellation id
        | 6 -> Constellations6.getConstellation id
        | 7 -> Constellations7.getConstellation id
        | 8 -> Constellations8.getConstellation id
        | 9 -> Constellations9.getConstellation id
        | 10 -> Constellations10.getConstellation id
        | 11 -> Constellations11.getConstellation id
        | 12 -> Constellations12.getConstellation id
        | 13 -> Constellations13.getConstellation id
        | 14 -> Constellations14.getConstellation id
        | 15 -> Constellations15.getConstellation id
        | 16 -> Constellations16.getConstellation id
        | 17 -> Constellations17.getConstellation id
        | 18 -> Constellations18.getConstellation id
        | 19 -> Constellations19.getConstellation id
        | 20 -> Constellations20.getConstellation id
        | 21 -> Constellations21.getConstellation id
        | 22 -> Constellations22.getConstellation id
        | 23 -> Constellations23.getConstellation id
        | 24 -> Constellations24.getConstellation id
        | 25 -> Constellations25.getConstellation id
        | 26 -> Constellations26.getConstellation id
        | 27 -> Constellations27.getConstellation id
        | 28 -> Constellations28.getConstellation id
        | 29 -> Constellations29.getConstellation id
        | 30 -> Constellations30.getConstellation id
        | 31 -> Constellations31.getConstellation id
        | 32 -> Constellations32.getConstellation id
        | 33 -> Constellations33.getConstellation id
        | 34 -> Constellations34.getConstellation id
        | 35 -> Constellations35.getConstellation id
        | 36 -> Constellations36.getConstellation id
        | 37 -> Constellations37.getConstellation id
        | 38 -> Constellations38.getConstellation id
        | 39 -> Constellations39.getConstellation id
        | 40 -> Constellations40.getConstellation id
        | 41 -> Constellations41.getConstellation id
        | 42 -> Constellations42.getConstellation id
        | 43 -> Constellations43.getConstellation id
        | 44 -> Constellations44.getConstellation id
        | 45 -> Constellations45.getConstellation id
        | 46 -> Constellations46.getConstellation id
        | 47 -> Constellations47.getConstellation id
        | 48 -> Constellations48.getConstellation id
        | 49 -> Constellations49.getConstellation id
        | 50 -> Constellations50.getConstellation id
        | 51 -> Constellations51.getConstellation id
        | 52 -> Constellations52.getConstellation id
        | 53 -> Constellations53.getConstellation id
        | 54 -> Constellations54.getConstellation id
        | 55 -> Constellations55.getConstellation id
        | 56 -> Constellations56.getConstellation id
        | 57 -> Constellations57.getConstellation id
        | 58 -> Constellations58.getConstellation id
        | 59 -> Constellations59.getConstellation id
        | 60 -> Constellations60.getConstellation id
        | 61 -> Constellations61.getConstellation id
        | 62 -> Constellations62.getConstellation id
        | 63 -> Constellations63.getConstellation id
        | 64 -> Constellations64.getConstellation id
        | 65 -> Constellations65.getConstellation id
        | 66 -> Constellations66.getConstellation id
        | 67 -> Constellations67.getConstellation id
        | 68 -> Constellations68.getConstellation id
        | 69 -> Constellations69.getConstellation id
        | 70 -> Constellations70.getConstellation id
        | 71 -> Constellations71.getConstellation id
        | 72 -> Constellations72.getConstellation id
        | 73 -> Constellations73.getConstellation id
        | 74 -> Constellations74.getConstellation id
        | 75 -> Constellations75.getConstellation id
        | 76 -> Constellations76.getConstellation id
        | 77 -> Constellations77.getConstellation id
        | 78 -> Constellations78.getConstellation id
        | 79 -> Constellations79.getConstellation id
        | 80 -> Constellations80.getConstellation id
        | 81 -> Constellations81.getConstellation id
        | 82 -> Constellations82.getConstellation id
        | 83 -> Constellations83.getConstellation id
        | 84 -> Constellations84.getConstellation id
        | 85 -> Constellations85.getConstellation id
        | 86 -> Constellations86.getConstellation id
        | 87 -> Constellations87.getConstellation id
        | 88 -> Constellations88.getConstellation id
        | 89 -> Constellations89.getConstellation id
        | 90 -> Constellations90.getConstellation id
        | 91 -> Constellations91.getConstellation id
        | 92 -> Constellations92.getConstellation id
        | 93 -> Constellations93.getConstellation id
        | 94 -> Constellations94.getConstellation id
        | 95 -> Constellations95.getConstellation id
        | 96 -> Constellations96.getConstellation id
        | _ -> None