namespace EsiStatics.Data.Universe
open System
open EsiStatics.Data.Entities
module  SolarSystems=
    let getSolarSystem id = 
      let bkt = id % 97
      match bkt with
        | 0 -> SolarSystems0.getSolarSystem id
        | 1 -> SolarSystems1.getSolarSystem id
        | 2 -> SolarSystems2.getSolarSystem id
        | 3 -> SolarSystems3.getSolarSystem id
        | 4 -> SolarSystems4.getSolarSystem id
        | 5 -> SolarSystems5.getSolarSystem id
        | 6 -> SolarSystems6.getSolarSystem id
        | 7 -> SolarSystems7.getSolarSystem id
        | 8 -> SolarSystems8.getSolarSystem id
        | 9 -> SolarSystems9.getSolarSystem id
        | 10 -> SolarSystems10.getSolarSystem id
        | 11 -> SolarSystems11.getSolarSystem id
        | 12 -> SolarSystems12.getSolarSystem id
        | 13 -> SolarSystems13.getSolarSystem id
        | 14 -> SolarSystems14.getSolarSystem id
        | 15 -> SolarSystems15.getSolarSystem id
        | 16 -> SolarSystems16.getSolarSystem id
        | 17 -> SolarSystems17.getSolarSystem id
        | 18 -> SolarSystems18.getSolarSystem id
        | 19 -> SolarSystems19.getSolarSystem id
        | 20 -> SolarSystems20.getSolarSystem id
        | 21 -> SolarSystems21.getSolarSystem id
        | 22 -> SolarSystems22.getSolarSystem id
        | 23 -> SolarSystems23.getSolarSystem id
        | 24 -> SolarSystems24.getSolarSystem id
        | 25 -> SolarSystems25.getSolarSystem id
        | 26 -> SolarSystems26.getSolarSystem id
        | 27 -> SolarSystems27.getSolarSystem id
        | 28 -> SolarSystems28.getSolarSystem id
        | 29 -> SolarSystems29.getSolarSystem id
        | 30 -> SolarSystems30.getSolarSystem id
        | 31 -> SolarSystems31.getSolarSystem id
        | 32 -> SolarSystems32.getSolarSystem id
        | 33 -> SolarSystems33.getSolarSystem id
        | 34 -> SolarSystems34.getSolarSystem id
        | 35 -> SolarSystems35.getSolarSystem id
        | 36 -> SolarSystems36.getSolarSystem id
        | 37 -> SolarSystems37.getSolarSystem id
        | 38 -> SolarSystems38.getSolarSystem id
        | 39 -> SolarSystems39.getSolarSystem id
        | 40 -> SolarSystems40.getSolarSystem id
        | 41 -> SolarSystems41.getSolarSystem id
        | 42 -> SolarSystems42.getSolarSystem id
        | 43 -> SolarSystems43.getSolarSystem id
        | 44 -> SolarSystems44.getSolarSystem id
        | 45 -> SolarSystems45.getSolarSystem id
        | 46 -> SolarSystems46.getSolarSystem id
        | 47 -> SolarSystems47.getSolarSystem id
        | 48 -> SolarSystems48.getSolarSystem id
        | 49 -> SolarSystems49.getSolarSystem id
        | 50 -> SolarSystems50.getSolarSystem id
        | 51 -> SolarSystems51.getSolarSystem id
        | 52 -> SolarSystems52.getSolarSystem id
        | 53 -> SolarSystems53.getSolarSystem id
        | 54 -> SolarSystems54.getSolarSystem id
        | 55 -> SolarSystems55.getSolarSystem id
        | 56 -> SolarSystems56.getSolarSystem id
        | 57 -> SolarSystems57.getSolarSystem id
        | 58 -> SolarSystems58.getSolarSystem id
        | 59 -> SolarSystems59.getSolarSystem id
        | 60 -> SolarSystems60.getSolarSystem id
        | 61 -> SolarSystems61.getSolarSystem id
        | 62 -> SolarSystems62.getSolarSystem id
        | 63 -> SolarSystems63.getSolarSystem id
        | 64 -> SolarSystems64.getSolarSystem id
        | 65 -> SolarSystems65.getSolarSystem id
        | 66 -> SolarSystems66.getSolarSystem id
        | 67 -> SolarSystems67.getSolarSystem id
        | 68 -> SolarSystems68.getSolarSystem id
        | 69 -> SolarSystems69.getSolarSystem id
        | 70 -> SolarSystems70.getSolarSystem id
        | 71 -> SolarSystems71.getSolarSystem id
        | 72 -> SolarSystems72.getSolarSystem id
        | 73 -> SolarSystems73.getSolarSystem id
        | 74 -> SolarSystems74.getSolarSystem id
        | 75 -> SolarSystems75.getSolarSystem id
        | 76 -> SolarSystems76.getSolarSystem id
        | 77 -> SolarSystems77.getSolarSystem id
        | 78 -> SolarSystems78.getSolarSystem id
        | 79 -> SolarSystems79.getSolarSystem id
        | 80 -> SolarSystems80.getSolarSystem id
        | 81 -> SolarSystems81.getSolarSystem id
        | 82 -> SolarSystems82.getSolarSystem id
        | 83 -> SolarSystems83.getSolarSystem id
        | 84 -> SolarSystems84.getSolarSystem id
        | 85 -> SolarSystems85.getSolarSystem id
        | 86 -> SolarSystems86.getSolarSystem id
        | 87 -> SolarSystems87.getSolarSystem id
        | 88 -> SolarSystems88.getSolarSystem id
        | 89 -> SolarSystems89.getSolarSystem id
        | 90 -> SolarSystems90.getSolarSystem id
        | 91 -> SolarSystems91.getSolarSystem id
        | 92 -> SolarSystems92.getSolarSystem id
        | 93 -> SolarSystems93.getSolarSystem id
        | 94 -> SolarSystems94.getSolarSystem id
        | 95 -> SolarSystems95.getSolarSystem id
        | 96 -> SolarSystems96.getSolarSystem id
        | _ -> None