namespace EsiStatics.Data.Universe
open System
open EsiStatics.Data.Entities
module  Stations=
    let getStation id = 
      let bkt = id % 97
      match bkt with
        | 0 -> Stations0.getStation id
        | 1 -> Stations1.getStation id
        | 2 -> Stations2.getStation id
        | 3 -> Stations3.getStation id
        | 4 -> Stations4.getStation id
        | 5 -> Stations5.getStation id
        | 6 -> Stations6.getStation id
        | 7 -> Stations7.getStation id
        | 8 -> Stations8.getStation id
        | 9 -> Stations9.getStation id
        | 10 -> Stations10.getStation id
        | 11 -> Stations11.getStation id
        | 12 -> Stations12.getStation id
        | 13 -> Stations13.getStation id
        | 14 -> Stations14.getStation id
        | 15 -> Stations15.getStation id
        | 16 -> Stations16.getStation id
        | 17 -> Stations17.getStation id
        | 18 -> Stations18.getStation id
        | 19 -> Stations19.getStation id
        | 20 -> Stations20.getStation id
        | 21 -> Stations21.getStation id
        | 22 -> Stations22.getStation id
        | 23 -> Stations23.getStation id
        | 24 -> Stations24.getStation id
        | 25 -> Stations25.getStation id
        | 26 -> Stations26.getStation id
        | 27 -> Stations27.getStation id
        | 28 -> Stations28.getStation id
        | 29 -> Stations29.getStation id
        | 30 -> Stations30.getStation id
        | 31 -> Stations31.getStation id
        | 32 -> Stations32.getStation id
        | 33 -> Stations33.getStation id
        | 34 -> Stations34.getStation id
        | 35 -> Stations35.getStation id
        | 36 -> Stations36.getStation id
        | 37 -> Stations37.getStation id
        | 38 -> Stations38.getStation id
        | 39 -> Stations39.getStation id
        | 40 -> Stations40.getStation id
        | 41 -> Stations41.getStation id
        | 42 -> Stations42.getStation id
        | 43 -> Stations43.getStation id
        | 44 -> Stations44.getStation id
        | 45 -> Stations45.getStation id
        | 46 -> Stations46.getStation id
        | 47 -> Stations47.getStation id
        | 48 -> Stations48.getStation id
        | 49 -> Stations49.getStation id
        | 50 -> Stations50.getStation id
        | 51 -> Stations51.getStation id
        | 52 -> Stations52.getStation id
        | 53 -> Stations53.getStation id
        | 54 -> Stations54.getStation id
        | 55 -> Stations55.getStation id
        | 56 -> Stations56.getStation id
        | 57 -> Stations57.getStation id
        | 58 -> Stations58.getStation id
        | 59 -> Stations59.getStation id
        | 60 -> Stations60.getStation id
        | 61 -> Stations61.getStation id
        | 62 -> Stations62.getStation id
        | 63 -> Stations63.getStation id
        | 64 -> Stations64.getStation id
        | 65 -> Stations65.getStation id
        | 66 -> Stations66.getStation id
        | 67 -> Stations67.getStation id
        | 68 -> Stations68.getStation id
        | 69 -> Stations69.getStation id
        | 70 -> Stations70.getStation id
        | 71 -> Stations71.getStation id
        | 72 -> Stations72.getStation id
        | 73 -> Stations73.getStation id
        | 74 -> Stations74.getStation id
        | 75 -> Stations75.getStation id
        | 76 -> Stations76.getStation id
        | 77 -> Stations77.getStation id
        | 78 -> Stations78.getStation id
        | 79 -> Stations79.getStation id
        | 80 -> Stations80.getStation id
        | 81 -> Stations81.getStation id
        | 82 -> Stations82.getStation id
        | 83 -> Stations83.getStation id
        | 84 -> Stations84.getStation id
        | 85 -> Stations85.getStation id
        | 86 -> Stations86.getStation id
        | 87 -> Stations87.getStation id
        | 88 -> Stations88.getStation id
        | 89 -> Stations89.getStation id
        | 90 -> Stations90.getStation id
        | 91 -> Stations91.getStation id
        | 92 -> Stations92.getStation id
        | 93 -> Stations93.getStation id
        | 94 -> Stations94.getStation id
        | 95 -> Stations95.getStation id
        | 96 -> Stations96.getStation id
        | _ -> None