namespace EsiStatics.Data.ItemTypes
open System
open EsiStatics.Data.Entities
module internal DogmaAttributes12=
    let getDogmaAttribute id = 
      match id with 
      | 1079 -> { DogmaAttributeData.id= 1079; name= "capacitorCapacityBonus"; description= "Autogenerated skill attribute, CapacitorCapacityBonus"; published= true; unitId= Some(105); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 109 -> { DogmaAttributeData.id= 109; name= "kineticDamageResonance"; description= "damage multiplier vs. kinetic damagers."; published= true; unitId= Some(108); defaultValue= 1.000000; stackable= false; highIsGood= false } |> Some
      | 1176 -> { DogmaAttributeData.id= 1176; name= "heatMed"; description= ""; published= true; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 12 -> { DogmaAttributeData.id= 12; name= "lowSlots"; description= "The number of low power slots on the ship."; published= true; unitId= Some(122); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1273 -> { DogmaAttributeData.id= 1273; name= "droneBandwidthLoad"; description= ""; published= true; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1370 -> { DogmaAttributeData.id= 1370; name= "baseScanRange"; description= "This is the lowest scan range value in AUs for probes under the revised probing system"; published= true; unitId= Some(135); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1467 -> { DogmaAttributeData.id= 1467; name= "armorThermalDamageResistanceBonus"; description= "Thermal damage resistance bonus for armor"; published= true; unitId= Some(124); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1564 -> { DogmaAttributeData.id= 1564; name= "specialIndustrialShipHoldCapacity"; description= "Capacity of industrial ship hold"; published= true; unitId= Some(9); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1661 -> { DogmaAttributeData.id= 1661; name= "entityRemoteECMBaseDuration"; description= "The base time between ECM bursts"; published= true; unitId= None; defaultValue= 300000.000000; stackable= true; highIsGood= true } |> Some
      | 1758 -> { DogmaAttributeData.id= 1758; name= "distributionID04"; description= "Distribution ID for global sov upgrades"; published= false; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1855 -> { DogmaAttributeData.id= 1855; name= "AI_IgnoreDronesBelowSignatureRadius"; description= "NPC'S with this attribute wont shoot drones with signature radius less than this value."; published= false; unitId= Some(1); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 1952 -> { DogmaAttributeData.id= 1952; name= "industryStructureCostBonus"; description= "Build cost multiplier"; published= true; unitId= Some(104); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 2049 -> { DogmaAttributeData.id= 2049; name= "entitySuperWeaponOptimalSignatureRadius"; description= "Used for chance based accuracy hit calculation for entity super weapon."; published= false; unitId= None; defaultValue= 20.000000; stackable= true; highIsGood= true } |> Some
      | 2243 -> { DogmaAttributeData.id= 2243; name= "fighterAbilityTackleWebSpeedPenaltyInterim"; description= ""; published= false; unitId= Some(124); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 2340 -> { DogmaAttributeData.id= 2340; name= "skillBonusFighterHangarSize"; description= ""; published= true; unitId= Some(121); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 2437 -> { DogmaAttributeData.id= 2437; name= "structureRigPDCapUseBonus"; description= ""; published= true; unitId= Some(105); defaultValue= 0.000000; stackable= true; highIsGood= false } |> Some
      | 2534 -> { DogmaAttributeData.id= 2534; name= "behaviorECMDischarge"; description= ""; published= false; unitId= Some(1); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 2631 -> { DogmaAttributeData.id= 2631; name= "behaviorEnergyNosferatuFalloff"; description= ""; published= false; unitId= Some(1); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 2728 -> { DogmaAttributeData.id= 2728; name= "moonAsteroidDecayDisplayValue"; description= "This attribute doesn't directly impact the asteroid decay, but is used to expose the decay time to the show-info window"; published= true; unitId= Some(129); defaultValue= 48.000000; stackable= true; highIsGood= true } |> Some
      | 2825 -> { DogmaAttributeData.id= 2825; name= "setBonusMimesis"; description= ""; published= true; unitId= Some(104); defaultValue= 1.000000; stackable= true; highIsGood= true } |> Some
      | 303 -> { DogmaAttributeData.id= 303; name= "aiPowerBonus"; description= "Autogenerated skill attribute, aiPowerBonus"; published= false; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 400 -> { DogmaAttributeData.id= 400; name= "missileStandardVelocityPecent"; description= "Missiles velocity multiplier"; published= false; unitId= None; defaultValue= 100.000000; stackable= true; highIsGood= true } |> Some
      | 497 -> { DogmaAttributeData.id= 497; name= "entityDefenderChance"; description= "% chance of entity to shoot defender at incoming missile"; published= false; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 594 -> { DogmaAttributeData.id= 594; name= "Die"; description= "Autogenerated skill attribute, cloakCapacitor Bonus"; published= false; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 691 -> { DogmaAttributeData.id= 691; name= "targetSwitchDelay"; description= "The amount of time after attacking a target that an entity will wait before switching to a new one."; published= false; unitId= Some(101); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 788 -> { DogmaAttributeData.id= 788; name= "maxScanDeviation"; description= "Maximum scan error"; published= true; unitId= Some(1); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 885 -> { DogmaAttributeData.id= 885; name= "consumptionQuantityBonus"; description= ""; published= true; unitId= Some(138); defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | 982 -> { DogmaAttributeData.id= 982; name= "canReceiveCloneJumps"; description= "Defines whether a ship has the functionality to allow it to receive clone jumps and host jump clones."; published= false; unitId= None; defaultValue= 0.000000; stackable= true; highIsGood= true } |> Some
      | _ -> None